Add support for loading private key from file
grafana/google-bigquery-datasource pull request #131
Opened 2022-06-27 21:43 UTC by hs-robertbecker

Prior, the private key needed to be embedded into the yaml config which is prone to failues by a faulty indentation. The option 'privateKeyFile' enables to read the private key from a file

2022-06-27 21:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/google-bigquery-datasource?pullRequest=131) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/google-bigquery-datasource?pullRequest=131) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/google-bigquery-datasource?pullRequest=131) it.</sub>

2022-06-29 13:42 UTC, dprokop reviewed
@hs-robertbecker thanks for the conribution!

I think this is an interesting addition. My suggestions for the UI are as follows:
1. Add an option to fill the JWT manually first. This should show an empty JWT form:


https://user-images.githubusercontent.com/2376619/176451072-d4e00727-feeb-44c1-9310-035b4975bd20.mov


2. In the form allow specifying file path instead of the key itself:

https://user-images.githubusercontent.com/2376619/176450786-1a243c36-9ad4-41fc-b75b-e7003b710b64.mov


@zoltanbedi any thoughts on this?

2022-06-29 13:42 UTC, dprokop commented on README.md
> +      privateKeyFile: '/etc/secrets/bigquery.pem'
```suggestion
      privateKeyPath: '/etc/secrets/bigquery.pem'
```

2022-06-30 22:41 UTC, hs-robertbecker commented
I added a new input field like @dprokop suggested. I have to work through the test cases before I will hand in the code for a proper PR
![Screen Shot 2022-06-30 at 3 38 45 PM](https://user-images.githubusercontent.com/108303362/176790402-2d2b74ec-68ce-4432-a64d-75635d071944.png)
![Screen Shot 2022-06-30 at 3 38 45 PM](https://user-images.githubusercontent.com/108303362/176790402-2d2b74ec-68ce-4432-a64d-75635d071944.png)
![Screen Shot 2022-06-30 at 3 39 30 PM](https://user-images.githubusercontent.com/108303362/176790404-bcfc1ea6-5849-4594-8ae3-b501206e2c04.png)
![Screen Shot 2022-06-30 at 3 39 30 PM](https://user-images.githubusercontent.com/108303362/176790404-bcfc1ea6-5849-4594-8ae3-b501206e2c04.png)
![Screen Shot 2022-06-30 at 3 39 37 PM](https://user-images.githubusercontent.com/108303362/176790408-81e64134-10de-4946-a2b1-8d89b81f34a1.png)
![Screen Shot 2022-06-30 at 3 39 37 PM](https://user-images.githubusercontent.com/108303362/176790408-81e64134-10de-4946-a2b1-8d89b81f34a1.png)

2022-07-04 21:31 UTC, hs-robertbecker commented
@dprokop @zoltanbedi 
I am done with the changes, all tests and linting seem to pass!

2022-07-06 11:56 UTC, zoltanbedi requested changes
Hi @hs-robertbecker,
Thanks for creating this pr. One more thing, can you please add your change to the CHANGELOG.MD as well. Other than that all looks good and works as expected.

2022-07-06 11:56 UTC, zoltanbedi commented on .gitignore
> +yarn.lock
Can you remove this change please?

2022-07-06 16:27 UTC, hs-robertbecker commented
@zoltanbedi 
✅ CHANGELOG updated
✅  gitignore file was changed to your request

2022-07-06 17:11 UTC, zoltanbedi commented on yarn.lock
> -  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.10.4.tgz#168da1a36e90da68ae8d49c0f1b48c7c6249213a"
@hs-robertbecker Can you please revert this change?

2022-07-06 17:12 UTC, zoltanbedi commented on .gitignore
> +dist/
Revert this as well please.

2022-07-06 17:28 UTC, zoltanbedi approved these changes
Thank you @hs-robertbecker!

2022-07-06 17:28 UTC, merged